{
 "title": "Pyrra - Detail",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "slo",
    "label": "SLO",
    "query": {
     "query": "label_values(pyrra_objective,slo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Objective",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pyrra_objective{slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Window",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pyrra_window{slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pyrra_availability{slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((pyrra_availability{slo=\"$slo\"} - pyrra_objective{slo=\"$slo\"})) / (1 - pyrra_objective{slo=\"$slo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pyrra_availability{slo=\"$slo\"} - pyrra_objective{slo=\"$slo\"})) / (1 - pyrra_objective{slo=\"$slo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pyrra_requests_total{slo=\"$slo\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pyrra_errors_total{slo=\"$slo\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}