{
 "title": "Ceph Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ceph Pool Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_pool_rd_bytes[$__rate_interval]) * on(pool_id) group_left(name) ceph_pool_metadata",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxmox VM Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id) (rate(pve_disk_read_bytes[5m]))\n* on(id) group_left(name) max(pve_guest_info) by(id,name)",
     "legendFormat": "{{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Proxmox Guest Network Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(pve_network_receive_bytes[$__rate_interval])) by (id)\n* on(id) group_left(name) max(pve_guest_info) by(id,name)",
     "legendFormat": "{{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "Ceph Pool Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_pool_wr_bytes[$__rate_interval]) * on(pool_id) group_left(name) ceph_pool_metadata",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxmox VM Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id) (rate(pve_disk_write_bytes[5m]))\n* on(id) group_left(name) max(pve_guest_info) by(id,name)",
     "legendFormat": "{{name}} - {{id}}"
    }
   ]
  }
 ]
}