{
 "title": "House",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(ha_climate_target_temperature_high_celsius) * 1.8 + 32",
     "legendFormat": "Maximum"
    },
    {
     "expr": "min(ha_climate_target_temperature_low_celsius) * 1.8 + 32",
     "legendFormat": "Minimum"
    },
    {
     "expr": "max(ha_climate_current_temperature_celsius) * 1.8 + 32",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Furnace State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "max(ha_climate_action) by (action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "House Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(avg_over_time(ha_sensor_temperature_celsius{friendly_name=~\".*temperature.*\"}[1h])) by (friendly_name) * 1.8) + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ha_sensor_battery_percent", "legendFormat": "{{friendly_name}}" }
   ]
  }
 ]
}