{
 "title": "Ceph",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_pool_bytes_used * on(pool_id) group_left(name) ceph_pool_metadata",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ceph_pool_bytes_used * on(pool_id) group_left(name) ceph_pool_metadata",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mimir & Loki Growth rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(ceph_pool_bytes_used{pool_id=\"14\"}[$__interval]) / 3",
     "legendFormat": "{{auto}}"
    },
    {
     "expr": "delta(ceph_pool_bytes_used{pool_id=\"14\"}[$__interval]) / 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Data Breakdown",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_pool_bytes_used * on(pool_id) group_left(name) ceph_pool_metadata",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ceph Active Daemon Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ceph_health_detail > 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ceph Active Daemon Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "ceph_daemon_health_metrics > 0", "legendFormat": "__auto" }
   ]
  }
 ]
}