{
 "title": "Homelab Maintenance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Harbor Downloads by Registry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(harbor_artifact_pulled{}[10m])) by(project_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{cluster=\"production\"}[8h]))) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd Fragmentation",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((etcd_mvcc_db_total_size_in_bytes{cluster=\"production\",job=\"kube-etcd\"} - etcd_mvcc_db_total_size_in_use_in_bytes{cluster=\"production\",job=\"kube-etcd\"}) / etcd_mvcc_db_total_size_in_bytes{cluster=\"production\",job=\"kube-etcd\"}) by (instance) * on(instance) group_left(node) label_replace(max(kube_node_info) by (internal_ip,node), \"instance\", \"$1:2379\",\"internal_ip\",\"(.*)\")",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}