{
 "title": "Request Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",container!=\"\",job=\"kube-state-metrics\"}) ",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!=\"\",container!=\"\",job=\"kubelet\"}[$__rate_interval]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{job=\"opencost\"} * on (node) kube_node_status_condition{cluster=\"production\",condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Cluster Worker Node Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info * on(pod,namespace,cluster) group_left() max(kube_pod_container_resource_requests{resource=\"cpu\",container!=\"\",job=\"kube-state-metrics\"}) by (pod,namespace,cluster) unless on(node) kube_node_role{role=\"control-plane\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_info * on(pod,namespace,cluster) group_left() sum(rate(container_cpu_usage_seconds_total{namespace!=\"\",container!=\"\",job=\"kubelet\"}[$__rate_interval])) by (pod,namespace,cluster) unless on(node) kube_node_role{role=\"control-plane\"})",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum((kube_node_info{} unless on(node) kube_node_role{role=\"control-plane\"}) * on(node) kube_node_status_allocatable{resource=\"cpu\",job=\"kube-state-metrics\",unit=\"core\"} * on(node) kube_node_status_condition{status=\"true\",condition=\"Ready\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU Request %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (pod,namespace) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\",resource=\"cpu\"}) by (pod,namespace)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Request %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod,namespace) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by (pod,namespace)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Expected CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg(max_over_time(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])[$__range:])) by (pod,namespace) * 0.8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expected Memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(max_over_time(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}[$__range])) by (pod,namespace) * 0.8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}