{
 "title": "ClusterPolicyReport Details",
 "tags": [ "Policy Reporter" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "policy",
    "label": "Policy",
    "query": "label_values(cluster_policy_report_result, policy)"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "label_values(cluster_policy_report_result, category)"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(cluster_policy_report_result, severity)"
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": "label_values(cluster_policy_report_result, kind)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(cluster_policy_report_result, source)"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Pass Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"pass\" }) by (pod))"
    }
   ]
  },
  {
   "title": "Policy Warning Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"warn\" }) by (pod))"
    }
   ]
  },
  {
   "title": "Policy Fail Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"fail\" }) by (pod))"
    }
   ]
  },
  {
   "title": "Policy Error Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"error\" }) by (pod))"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\" } > 0) by (status, pod)) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Passed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", source=~\"$source\", status=\"pass\" }) by (pod,policy,rule,kind,name,status,severity,category,source)) by (policy,rule,kind,name,status,severity,category,source)"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"fail\" }) by (pod, policy,rule,kind,name,status,severity,category,source)) by (policy,rule,kind,name,status,severity,category,source)"
    }
   ]
  },
  {
   "title": "Warning Resources",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"warn\" }) by (pod,policy,rule,kind,name,status,severity,category,source)) by (policy,rule,kind,name,status,severity,category,source)"
    }
   ]
  },
  {
   "title": "Errored Resources",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=\"warn\" }) by (pod, policy,rule,kind,name,status,severity,category,source)) by (policy,rule,kind,name,status,severity,category,source)"
    }
   ]
  }
 ]
}