{
 "title": "PolicyReport Details",
 "tags": [ "Policy Reporter" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "policy",
    "label": "Policy",
    "query": "label_values(policy_report_result, policy)"
   },
   {
    "name": "rule",
    "label": "Rule",
    "query": {
     "query": "label_values(policy_report_result{policy=~\"$policy\"},rule)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": "label_values(policy_report_result, category)"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(policy_report_result, severity)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(policy_report_result, exported_namespace)"
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": "label_values(policy_report_result, kind)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(policy_report_result, source)"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Pass Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"pass\" } > 0) by (exported_namespace, pod)) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Policy Fail Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"fail\" } > 0) by (exported_namespace, pod)) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Policy Warning Status",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"warn\" } > 0)  by (exported_namespace, pod)) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Policy Error Status",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"error\" } > 0) by (exported_namespace, pod)) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\" } > 0) by (status, pod, exported_namespace)) by (status, exported_namespace)",
     "legendFormat": "{{exported_namespace}} {{ status }}"
    }
   ]
  },
  {
   "title": "Passed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"pass\" }) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"fail\" }) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)"
    }
   ]
  },
  {
   "title": "Warning Resources",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"warn\" }) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)) by (exported_namespace,category,policy,rule,kind,name,severity,status,source )"
    }
   ]
  },
  {
   "title": "Errored Resources",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", rule=~\"$rule\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"error\" }) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)"
    }
   ]
  }
 ]
}